# Uncomment the next line to define a global platform for your project
platform :osx, '10.15'

target 'code-snippets-extractor' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'Slang', '~> 0.1'

end
